services:
  djangotest:
    image: envalue/djangotest
    build: .
    ports:
      - "8082:8082"
    volumes:
      - ./:/app
    environment:
      PGSERVICEFILE: /app/.pg_service.conf
#    secrets:
#      - rsa-private-key
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - djangotest_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  djangotest_data:
    external: true

#secrets:
#  rsa-private-key:
#    file: ./oidc.key