services:
  djangotest:
    image: djangotest
    build: .
    ports:
      - "8082:8082"
    volumes:
      - ./:/app
    environment:
      PGSERVICEFILE: /app/.pg_service.conf
    secrets:
      - eddsa-private-key
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - djangotest_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  djangotest_data:
    external: true

secrets:
  eddsa-private-key:
    file: ./eddsa-private-key