services:
  djangotest:
    image: envalue/djangotest
    build: .
    ports:
      - "8082:8082"
    volumes:
      - ./:/app
    environment:
      PGSERVICEFILE: /app/.pg_service.conf
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - djangotest_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  djangotest_data:
    external: true